"""add compression, password, membership fields

Revision ID: 34c4c29ff44e
Revises: cf26315fa740
Create Date: 2026-05-27 18:26:42.363670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34c4c29ff44e'
down_revision = 'cf26315fa740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('membership_type', sa.String(length=16), nullable=False),
    sa.Column('granted_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_compressed', sa.Boolean(), nullable=False, server_default=sa.text("0")))
        batch_op.add_column(sa.Column('is_password_protected', sa.Boolean(), nullable=False, server_default=sa.text("0")))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('requires_membership', sa.Boolean(), nullable=False, server_default=sa.text("0")))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_column('requires_membership')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('is_password_protected')
        batch_op.drop_column('is_compressed')
        batch_op.drop_column('original_size')

    op.drop_table('memberships')
    # ### end Alembic commands ###
